spring.application.name=api-gateway

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8081/eureka

logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

spring.cloud.gateway.server.webmvc.routes[0].id=users
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=documents
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://document-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/documents/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=version-control
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://version-control-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/versions/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1