spring.application.name=discovery-server

server.port=${SERVER_PORT:8080}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=${DISCOVERY_URL}

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n