spring.application.name=document-service

server.port=${SERVER_PORT:8080}

eureka.client.service-url.defaultZone=${DISCOVERY_URL}

logging.pattern.console=%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n

spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.mail.from=${MAIL_FROM:no-reply@collab-documents.local}
spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}

logging.file.name=logs/document_service.log

spring.mvc.static-path-pattern=NONE
